print ("¿En qué ciudad vives?")
ciudad = input()
print ("Describe tu ciudad en 1 adjetivo")
adjetivo = input()
print ("¿Compartes tu casa con alguien? Nombra a una persona")
roomie = input()
print ("Qué te gusta hacer en el verano?")
actividad = input()
print ("¿Qué lugar tienes planeado visitar proximamente?")
lugar = input()
print ("¿Cómo te sientes al respecto?")
emoción = input()
print ("Vivo en " + ciudad + ", es una ciudad muy " + adjetivo + ".")
print ("Comparto mi casa con " + roomie + ".")
print ("En el verano me encanta " + actividad + ".")
print ("Pronto visitaré " + lugar + " y estoy " + emoción + ".")