print ("¿Cuál es tu nombre?")
nombre = input()
print ("¿Cuál es el puesto para el que te preparas en Generation?")
puesto = input()
print ("Describe a tu compañero con un adjetivo")
adjcomp = input()
print ("Describe a tu profesor con un adjetivo")
adjprof = input()
print ("¿Qué comiste hoy?")
comida1 = input()
print ("¿Con qué lo acompañaste?")
comida2 = input()
print ("Dime un sentimiento que experimentaste en el curso")
sentimiento = input()
print (nombre + " ha comenzado hoy su primer curso en Generation.")
print ("Se están formando como " + puesto)
print ("Su compañero les pareció muy " + adjcomp + ", pero su profesor era cuando menos, " + adjprof + ".")
print ("Para comer comen " + comida1 + " y " + comida2 + " mientras repasan sus notas.")
print ("Sienten " + sentimiento + " pero están decididos a completar el curso.")